`/src/utils` に道具系ファイルを追加
corvvs/webserv pull request #12
Opened 2022-06-23 09:58 UTC by corvvs

- `http.hpp, http.cpp`のもろもろ
  - 定数, 型定義, enumなど。
- `debug_out, debug_err`関数, `DXOUT, DXERR`マクロ
  - デバッグ用。
- `IndexRange`クラス
  - インデックスの「範囲」を表す`std::pair`の変種。
- `CharFilter`クラス
  - 「文字集合」によるマッチングを簡単に行うための文字集合クラス。
- `LightString<T>`クラス
  - 別の文字列の一部分だけを参照し, それをあたかも独立した文字列かのように色々するためのクラス。

2022-06-23 13:51 UTC, ryo-manba requested changes

2022-06-23 13:51 UTC, ryo-manba commented on src/utils/LightString.hpp
> +        }
iのデクリメントはfor文のカッコの中でもいいかもですね。

あとbreakの波括弧だけ1行で書いてあるのがちょっぴり違和感を感じますが、
後ほどフォーマッター書けるのであれば、気にしなくていいですね。

2022-06-23 13:51 UTC, ryo-manba commented on src/utils/LightString.hpp
> +        }
デクリメントはfor文のカッコの中でもいいかもですね。

2022-06-23 13:51 UTC, ryo-manba commented on src/utils/LightString.hpp
> +        return npos;
デクリメントはfor文のカッコの中でもいいかもですね。

2022-06-23 13:51 UTC, ryo-manba commented on src/utils/CharFilter.cpp
> +        uint8_t c = i;
`uint64_t`, `uint8_t` は、C++11からですかね。
イケてないですが、unsigned long と unsigned short にする必要がありそうです。

2022-06-23 14:31 UTC, corvvs commented on src/utils/CharFilter.cpp
> +        uint8_t c = i;
`unsigned char` x 8 のほうがマシかもしれない。

2022-06-23 14:33 UTC, corvvs commented on src/utils/LightString.hpp
> +        }
`for`にデクリメントを移す場合, 初期化と条件の部分をやや煩雑な形に変更することになるので、それを避けたいです。

2022-06-23 14:33 UTC, corvvs commented on src/utils/LightString.hpp
> +        return npos;
`for`にデクリメントを移す場合, 初期化と条件の部分をやや煩雑な形に変更することになるので、それを避けたいです。

2022-06-24 11:01 UTC, corvvs commented
fdc381d
`LightString`は`std::string`への参照を持っていたが, 参照は一度リンクすると他の実態にリンクし直すことができない。
よって代入演算子の実装に不都合がある。

参照ではなくポインタを持つことでリンクし直せるようにした。

2022-06-25 01:46 UTC, nao215912 commented on src/utils/LightString.hpp
> +        first = last;
動作的には問題ないと思うんですけど、
first = last = blank_str.size();
の方が良さそう

2022-06-25 01:46 UTC, nao215912 commented on src/utils/CharFilter.cpp
> +    memset(filter, 0, 32);
memset(filter, 0, ELEMS);
の方が良さそう

2022-06-25 01:46 UTC, nao215912 commented on src/utils/CharFilter.cpp
> +        memcpy(filter, rhs.filter, 32);
memset(filter, 0, ELEMS);
の方が良さそう

2022-06-25 01:46 UTC, nao215912 commented on src/utils/CharFilter.cpp
> +        filter[(c >> 3)] |= (unsigned int)1 << (c & (((unsigned int)1 << 3) - 1));
filter[(c >> 3)] は　unsigned charが8bitだからだろ思う
(c & (((unsigned int)1 << 3) - 1))は下位3bitを取り出していると思う
(unsigned int)1 << (c & (((unsigned int)1 << 3) - 1))よくわからん

2022-06-25 03:13 UTC, corvvs commented on src/utils/CharFilter.cpp
> +        filter[(c >> 3)] |= (unsigned int)1 << (c & (((unsigned int)1 << 3) - 1));
最終的に使いたいのは`1 << 下位3bit`なのでOk.

2022-06-26 09:03 UTC, ryo-manba approved these changes
後はフォーマッターかけたらokです！

2022-06-28 01:23 UTC, nao215912 approved these changes

2022-06-28 01:33 UTC, merged