[WIP]#111 ルーティングの実装
corvvs/webserv pull request #133
Opened 2022-08-02 11:20 UTC by ryo-manba

#### 概要
ルーティングを実装する。

2022-08-04 13:24 UTC, corvvs requested changes

2022-08-04 13:24 UTC, corvvs commented on src/router/IRequestMatcher.hpp
> +#ifndef IREQUESTMATCHER_HPP
`/src/interface/IRequestMatcher.hpp`にあるものとの統合をお願いします。

2022-08-04 13:50 UTC, ryo-manba commented on src/router/IRequestMatcher.hpp
> +#ifndef IREQUESTMATCHER_HPP
ん、これって今WIPになってるプルリクに合わせるってことですか？
それともInterfaceディレクトリにファイル移動するだけって話でしょうか？(ファイル移動はしました)

2022-08-04 13:52 UTC, ryo-manba commented on src/router/IRequestMatcher.hpp
> +#ifndef IREQUESTMATCHER_HPP
新たに追加しないと対応できないものもあったので、逆に今の実装に合わせてもらえると助かります

2022-08-04 14:06 UTC, corvvs approved these changes

2022-08-05 14:10 UTC, nao215912 approved these changes

2022-08-05 14:31 UTC, merged