WIP: expservからwebservへのソースコード同期: `src/communucation/*`
corvvs/webserv pull request #47
Opened 2022-07-06 13:53 UTC by corvvs

2022-07-07 07:50 UTC, ryo-manba requested changes

2022-07-07 08:46 UTC, corvvs commented on src/communication/HeaderHTTP.cpp
> +
このマクロはhppではなくcppで定義されているので、このファイル内でしか使用できず、従ってご指摘のような影響はほとんどないと思います。

2022-07-07 08:46 UTC, corvvs commented on src/communication/ControlHeaderHTTP.hpp
> +    typedef std::map<parameter_key_type, parameter_value_type> parameter_dict;
HTTPヘッダの名前(キー)は大文字小文字を区別しないので、std::mapで同一性判定をするためには正規化する(=大文字小文字を揃える)必要があります。
`LightString`は、既存の文字列の一部分のみを保持しますが、その性質上文字列の変更ができません。
よって、キーに`LightString`を使うのは難しいです。

一方、値(バリュー)は、とりあえずこの時点では変更の必要がないので、コピーコストを鑑みて`LightString`にしています。

2022-07-07 08:59 UTC, corvvs commented on src/communication/Connection.cpp
> +}
現時点のコメント・実装内容はそうなっていますが、
TODOとしてはこの関数内でタイムアウトを検出するための処理をする想定です。

現状のタイムアウト処理では「10秒に1バイト送ってくる」ような攻撃に対応できないので、
「受信バイト数/時間」のような指標を使う必要があります。
そのような指標の計算と更新もこの関数で行いたいので、
特定の変数の更新を意味する名前をつけるのはちょっと気が進みません。

2022-07-07 09:02 UTC, corvvs commented on src/communication/RequestHTTP.cpp
> +    this->mid += s_o_s;
`start of status-line`の略でしたが、わかりにくい＆現状にそぐわないので、変更します。

2022-07-07 09:08 UTC, corvvs commented on src/communication/ChunkedBody.cpp
> +    rv.reserve(size());
`reserve`は`size`ではなく`capacity`を増やすための関数なので、この書き方には意味があります。

2022-07-07 09:09 UTC, corvvs commented on src/communication/HeaderHTTP.cpp
> +    }
内側の`for`で外側の`for`の`it`を使う予定がなかったので、同じ名前にしていますが、
わかりにくければ変更します。

2022-07-07 13:16 UTC, ryo-manba approved these changes

2022-07-08 03:16 UTC, nao215912 approved these changes

2022-07-08 03:18 UTC, merged