オブザーバはソケットライクにイベント種別を通知 & タイムアウトもnotifyで通知
corvvs/webserv pull request #73
Opened 2022-07-15 07:23 UTC by corvvs

2022-07-15 12:20 UTC, ryo-manba requested changes

2022-07-15 12:20 UTC, ryo-manba commented on src/event/Eventkqueueloop.cpp
> +        }
if文の中で変数定義した方が自然な気がします。
細かいかもしれませんが、const参照とconstポインタでもいいかもしれませんね。
 https://qiita.com/ktetsuo/items/9edc244f544ffedf0b28

全体を通して似たような処理があると思うので、変更していただけるようでしたら、
まとめて改修お願いいします。(全てにコメントつけると多くなってしまうので)

2022-07-15 12:20 UTC, ryo-manba commented on src/event/Eventkqueueloop.cpp
> +    for (update_queue::size_type i = 0; i < upqueue.size(); ++i) {
ただの疑問ですが、イテレータから添え字アクセスに変更した理由はあったりしますか？

2022-07-15 12:20 UTC, ryo-manba commented on src/event/Eventpollloop.cpp
> +    }
どういう処理をしているか説明していただけるとありがたいです。
(特にmaskのところ)

2022-07-15 12:54 UTC, corvvs commented on src/communication/Channel.cpp
> +    (void)epoch;
慣用的にUNIX時間のことを指すと思ってます
https://ja.wikipedia.org/wiki/UNIX%E6%99%82%E9%96%93
(UNIXエポックからの経過秒数を「エポック」と読んでるノリ)

2022-07-15 12:55 UTC, corvvs commented on src/event/Eventkqueueloop.cpp
> +    for (update_queue::size_type i = 0; i < upqueue.size(); ++i) {
このループ中に限らない話ですが、ループの中の処理が原因でループ対象のvectorが伸びることがあり、
そこで再確保が起きてしまうとイテレータが無効化されるのでクラッシュします。
・・・というバグを昨日実際に踏みました。

2022-07-15 12:58 UTC, corvvs commented on src/event/Eventpollloop.cpp
> +    }
`mask(movequeue[i].cat)`は第`b`ビットのみが立っている整数だと思ってください。

- `movequeue[i].in`がtrueの時 -> 第`b`ビットを確実にオンにしたい
  - ビットORで確実にオンにできる。
- `movequeue[i].in`がfalseの時 -> 第`b`ビットを確実にオフにしたい
  - ビットORの後でさらにビットXORすると、一旦オンにしてから反転するので確実にオフになる。

2022-07-15 13:50 UTC, ryo-manba commented on src/event/Eventkqueueloop.cpp
> +        }
失礼しました。
 > t_fd fd           = upqueue[i].fd;

を対象にしています。
おそらくfdって書き換わることないですよね

2022-07-15 13:51 UTC, corvvs commented on src/event/Eventkqueueloop.cpp
> +        }
↑わかりました。
constを付けることには依存ないですが、参照にはしなくてよさそうな気がします。

2022-07-15 14:46 UTC, ryo-manba commented on src/event/Eventkqueueloop.cpp
> +        }
`t_fd` って `int` の typedefでしたね。了解しました。

2022-07-16 02:18 UTC, ryo-manba approved these changes

2022-07-16 04:42 UTC, nao215912 approved these changes

2022-07-16 05:57 UTC, merged