ラウンドトリップによるHTTP接続の状態管理
corvvs/webserv pull request #75
Opened 2022-07-17 02:09 UTC by corvvs

2022-07-18 13:05 UTC, ryo-manba requested changes

2022-07-18 13:05 UTC, ryo-manba commented on src/communication/RequestHTTP.hpp
> +    RoutingParameters cp;
(提案) 細かいかもしれませんが、この場合 `cp` よりも `rp` の方が変数名としては適切ですかね。

2022-07-18 13:05 UTC, ryo-manba commented on src/communication/RoundTrip.cpp
> +        const extra_buffer_type::size_type n = std::min(extra_buffer.size(), (extra_buffer_type::size_type)1024);
> assert(extra_buffer.empty() == false);

(質問) emptyじゃなかったら `assert` を呼ぶのはなぜですか？

2022-07-18 13:54 UTC, corvvs commented on src/communication/RoundTrip.cpp
> +        const extra_buffer_type::size_type n = std::min(extra_buffer.size(), (extra_buffer_type::size_type)1024);
emptyだったら止まります。

2022-07-18 14:42 UTC, ryo-manba commented on src/communication/RoundTrip.cpp
> +        const extra_buffer_type::size_type n = std::min(extra_buffer.size(), (extra_buffer_type::size_type)1024);
あー、 条件が満たされないときに `assert` 投げられるのか。勘違いしてました。

2022-07-18 18:30 UTC, corvvs commented on src/communication/RoundTrip.cpp
> +        const extra_buffer_type::size_type n = std::min(extra_buffer.size(), (extra_buffer_type::size_type)1024);
とはいえ紛らわしい書き方だったので条件を変更しました。

2022-07-18 23:40 UTC, ryo-manba approved these changes

2022-07-19 04:17 UTC, nao215912 approved these changes

2022-07-19 04:24 UTC, merged